plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
//    id 'com.google.android.gms.oss-licenses-plugin'
}

android {
    compileSdk 35
    namespace "com.itsvks.layouteditor"

    defaultConfig {
        //applicationId "com.itsvks.layouteditor"
        minSdk 26
        targetSdk 34
        versionCode 8
        versionName project.versionName
    }

    signingConfigs {
        release {
            storeFile file("../key-layout-editor.keystore")
            storePassword "itsvks"
            keyAlias "vivek"
            keyPassword "itsvks"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            debuggable false
        }
        debug {
            signingConfig signingConfigs.release
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        //coreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    packagingOptions {
        pickFirst "license/README.dom.txt"
        exclude "license/LICENSE.dom-documentation.txt"
        exclude "license/NOTICE"
        exclude "license/LICENSE.dom-software.txt"
        exclude "license/LICENSE"
    }
}

dependencies {
    def lifecycle_version = '2.7.0'
    def activity_version = '1.8.2'

    //coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")

    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.activity.ktx

    implementation libs.androidx.appcompat.v161
    implementation libs.androidx.constraintlayout.v214
    implementation libs.androidx.core.ktx.v1120
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.recyclerview.v132
    implementation libs.androidx.viewpager2.v110beta02
    implementation libs.androidx.palette.ktx

    implementation libs.google.material
    implementation libs.play.services.oss.licenses
    implementation libs.gson.v2101
    implementation libs.utilcodex
    implementation libs.common.glide
    implementation libs.zoomage
    implementation libs.colorpickerview

    implementation platform('io.github.Rosemoe.sora-editor:bom:0.23.5')
    implementation "io.github.Rosemoe.sora-editor:editor"
    implementation "io.github.Rosemoe.sora-editor:language-textmate"

    implementation libs.commons.text

    implementation libs.common.io

    implementation(projects.layouteditor.vectormaster)
    implementation(projects.common)

    //causes strict mode violation
    // debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.13'
}
